---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: hjacobs/kube-janitor:20.10.0
    kbld.carvel.dev/origins: |
      - resolved:
          tag: 20.10.0
          url: hjacobs/kube-janitor:20.10.0
  image: index.docker.io/hjacobs/kube-janitor@sha256:47d536e688416af0dbc5f5275cfb39f452f9ccb5014d4a55dbd2316741ed228b
kind: ImagesLock
